// ------ BASIC INCLUDES --- //

#include <a_samp>
#include <progress>

#define YSI_YES_HEAP_MALLOC

#include <YSI_Coding\y_timers>
#include <YSI_Coding\y_hooks>
#include <crashdetect>
#include <streamer>
#include <newcallbacks>
#include <Pawn.CMD>
#include <a_mysql>
#include <string>
#include <core>
#include <float>
#include <mSelection>

// ------ MODULES --- //
#include "../gamemodes/modules/player_variables.inc"
#include "../gamemodes/modules/brain.inc"
#include "../gamemodes/modules/news.inc"
#include "../gamemodes/modules/callbacks.inc"
#include "../gamemodes/modules/atajos.inc"
#include "../gamemodes/modules/colores.inc"
#include "../gamemodes/modules/forwards.inc"
#include "../gamemodes/modules/dialogs.inc"
#include "../gamemodes/modules/login.inc"
#include "../gamemodes/modules/database.inc"
#include "../gamemodes/modules/config.inc"